version: '3.8'

services:
  web:
    image: rpontual/tech-blog:latest
    #command: ["npm", "run", "seed"]
    command: ['npm', 'run', 'start']
    depends_on:
      - db
    ports:
      - '3001:3001'
    environment:
      DB_NAME: 'tech_blog_db'
      DB_USER: 'postgres'
      DB_PASSWORD: '123456'
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_LOGGING: 'true'
      SESSION_SECRET: 'this_is_a_secret'
      SESSION_MAX_AGE: '3000000'

  db:
    image: 'postgres:16-alpine3.19'
    restart: always
    environment:
      POSTGRES_DB: 'tech_blog_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456'

    volumes:
      - ./database/postgres16:/var/lib/postgresql/data
